CREATE TABLE [dbo].[TriggersToDisable](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TableName] [varchar](10) NULL,
	[SchemaName] [varchar](10) NULL,
	[TriggerName] [varchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO